package com.futeh.posng.message.visa;

import com.futeh.posng.message.BitMapField;
import com.futeh.posng.message.Composite;

import static com.futeh.posng.DataElements.*;

public class Base1 {

    public Composite create() {
        Composite composite = new Composite()
                .set(0, b_num(4).desc("MTI"))
                .set(1, new BitMapField(16).desc("bitmap"))
                .set(2, b_num(19, HH).desc("PAN"))
                .set(3, b_num(6).desc("processing code"))
                .set(4, b_num(12).desc("acquirer amount"))
                .set(5, b_num(12).desc("settlement amount"))
                .set(6, b_num(12).desc("billing amount"))
                .set(7, b_num(7).desc("transmission data time"))
                .set(8, b_num(8).desc("billing fee"), b_num(8).desc("settlement conversion rate"))
                .set(10, b_num(8).desc("billing conversion rate"))
                .set(11, b_num(6).desc("system trace number"))
                .set(12, b_num(6).desc("local time"))
                .set(13, b_num(4).desc("local date"))
                .set(14, b_num(4).desc("expiration date"))
                .set(15, b_num(4).desc("settlement date"))
                .set(16, b_num(4).desc("conversion date"))
                .set(17, b_num(4).desc("capture date"))
                .set(18, b_num(4).desc("mcc"))
                .set(19, b_num(3).desc("acquirer institution country code"))
                .set(20, b_num(3).desc("pan extended country code"))
                .set(21, b_num(3).desc("forwarding institution country code"))
                .set(22, b_num(4).desc("pos entry mode").rightPadded('0'))
                .set(23, b_num(3).desc("card sequence number"))
                .set(24, b_num(3).desc("network international id"))
                .set(25, b_num(2).desc("pos condition code"))
                .set(26, b_num(2).desc("pos pin capture mode"))
                .set(27, b_num(1).desc("auth id resp len"))
                .set(28, e_amt(9).desc("transaction fee"))
                .set(32, b_num(11, H).desc("acquiring institution id code"))
                .set(33, b_num(11, H).desc("forwarding institution id code"))
                .set(34, bin(1002, H).desc("electronic commerce data (TLV format)"))
                .set(35, b_num(37, H).desc("track 2 data"))
                .set(37, e_char(12).desc("retrieval reference number"))
                .set(38, e_char(6).desc("auth code"))
                .set(39, e_char(2).desc("response code"))
                .set(40, e_char(3).desc("svc"), e_char(8).desc("card acceptor terminal id"))
                .set(42, e_char(15).desc("card acceptor id"))
                .set(43, e_char(40).desc("card acceptor name/location"))
                .set(44, new Composite().dataLength(H)
                                .set(1, e_char(1).desc("response source/reason code"))
                                .set(2, e_char(1).desc("address verification result code"))
                                .set(3, e_char(1).desc("reserved"))
                                .set(4, e_char(1).desc("reserved"))
                                .set(5, e_char(1).desc("cvv/icvv results code"))
                                .set(6, e_char(2).desc("PACM diversion level code"))
                                .set(7, e_char(1).desc("PACM diversion reason code"))
                                .set(8, e_char(1).desc("card authentication results code"))
                                .set(9, e_char(1).desc("reserved"))
                                .set(10, e_char(1).desc("cvv2 results code"))
                                .set(11, e_char(2).desc("original response code"))
                                .set(12, e_char(1).desc("check settlement code (US only)"))
                                .set(13, e_char(1).desc("CAVV result code"))
                                .set(14, e_char(4).desc("response reason code"))
                                .set(15, e_char(4).desc("primary account number, last four digits"))
                                .set(16, e_char(1).desc("CVM requirement for PIN-less"))
                        )
                .set(45, e_char(76, H).desc("track 1 data"))
                .set(46, e_char(99, H).desc("amounts, fees"))
                .set(48, bin(255, H).desc("additional data - private"))
                .set(49, b_num(3).desc("currency code, transaction"))
                .set(50, b_num(3).desc("currency code, settlement"))
                .set(51, b_num(3).desc("currency code, billing"))
                .set(52, binary(8).desc("PIN data"))
                .set(53, b_num(16).desc("security-related control information"))
                .set(54, e_char(120, H).desc("additional amounts"))
                .set(55, bin(255, H).desc("integrate circuit card related data"))
                .set(56, e_char(255, H).desc("customer related data"))
                .set(59, e_char(14, H).desc("national point-of-service geographic data"))
                .set(60, b_num(12, H).desc("additional POS information"))
                .set(61, b_num(36, H).desc("other amounts"))
                .set(62, new Composite().dataLength(H)
                    .set(0, new BitMapField(8))
                    .set(1, e_char(1).desc("authorization characteristics indicator")))
                .set(63, new Composite().dataLength(H)
                        .set(0, new BitMapField(8))
                        .set(1, b_num(4).desc("network identification code"))
                        .set(2, b_num(4).desc("time (preauth time limit)")))
                .set(66, b_num(1).desc("settlement code"))
                .set(68, b_num(3).desc("receiving institution country code"))
                .set(69, b_num(3).desc("settlement institution country code"))
                .set(70, b_num(3).desc("network management information code"))
                .set(73, b_num(6).desc("data, action"))
                .set(74, b_num(10).desc("credits, number"))
                .set(75, b_num(10).desc("credits, reversal number"))
                .set(76, b_num(10).desc("debits, number"))
                .set(77, b_num(10).desc("debits, reversal number"))
                .set(86, b_num(16).desc("credits, amount"))
                .set(87, b_num(16).desc("credits, reversal amount"))
                .set(88, b_num(16).desc("debits, amount"))
                .set(89, b_num(16).desc("debits, reversal amount"))
                .set(90, b_num(42).desc("original data element"))
                .set(91, e_char(1).desc("file update code"))
                .set(92, e_char(2).desc("file security code"))
                .set(95, e_char(42).desc("replacement amounts"))
                .set(96, binary(8).desc("message security code"))
                .set(97, e_char(17).desc("amount, net settlement"))
                .set(99, b_num(11, H).desc("settlement institution identification code"))
                .set(100, b_num(11, H).desc("receiving institution identification code"))
                .set(101, e_char(17, H).desc("file name"))
                .set(102, e_char(28, H).desc("account identification 1"))
                .set(103, e_char(28, H).desc("account identification 2"))
                .set(104, binary(255, H).desc("transaction description and transaction specific data"))
                .set(105, binary(16).desc("double-length DES key (Triple DES)"))
                .set(110, binary(65535, HH).desc("encryption data"))
                .set(114, binary(65535, HH).desc("domestic and localized data"))
                .set(115, e_char(65535, H).desc("additional trace data"))
                .set(116, binary(255, H).desc("card issuer reference data"))
                .set(117, e_char(255, H).desc("national used"))
                .set(118, e_char(255, H).desc("intra-country used"))
                .set(119, e_char(255, H).desc("settlement service data"))
                .set(120, binary(255, HH).desc("auxiliary transaction data"))
                .set(123, binary(255, H).desc("verification data"))
                .set(125, binary(255, H).desc("supporting information"))
                .set(126, binary(255, H).desc("visa private-use"))
                .set(127, binary(255, H).desc("file records: action and data"))
                .set(130, binary(3, H).desc("terminal capability profile"))
                .set(131, binary(5, H).desc("terminal verification result"))
                .set(132, binary(4).desc("unpredictable number"))
                .set(133, e_char(8).desc("terminal serial number"))
                .set(134, binary(255, H).desc("visa discretionary data"))
                .set(135, binary(15, H).desc("issuer discretionary data"))
                .set(136, binary(16).desc("cryptogram"))
                .set(137, binary(4).desc("application transaction counter"))
                .set(138, binary(2).desc("application interchange profile"))
                .set(139, binary(10).desc("arpc response cryptogram and code"))
                .set(140, binary(255, H).desc("issuer authentication data"))
                .set(142, binary(255, H).desc("issuer script"))
                .set(143, binary(20, H).desc("issuer script results"))
                .set(144, b_num(2).desc("cryptogram transaction type"))
                .set(145, b_num(3).desc("terminal country code"))
                .set(146, b_num(6).desc("terminal transaction date"))
                .set(147, b_num(12).desc("cryptogram amount"))
                .set(148, b_num(3).desc("cryptogram currency code"))
                .set(149, b_num(12).desc("cryptogram cashback amount"))
                ;


        return composite;
    }
}
